### ISSUE TITLE
Not working on RTX 3060 and RTX 3090

### ISSUE THREAD

**Issue by aafaqin** [wmcnally/kapao#14]
I used the installation instructions with conda on RTX 3060 and RTX 3090.
Cuda 11.4 Ubuntu 20 and 21 both. Getting this error.

`/kapao$ python demos/video.py --yt-id nrchfeybHmw --imgsz 1024 --weights kapao_l_coco.pt --conf-thres-kp 0.01 --kp-obj --face --start 56 --end 72 --display
Downloading demo video...
Done.
/home/beltech/anaconda3/envs/kapao2/lib/python3.6/site-packages/torch/cuda/__init__.py:106: UserWarning: 
NVIDIA GeForce RTX 3060 Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3060 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Using device: cuda:0
Traceback (most recent call last):
  File "demos/video.py", line 115, in <module>
    model = attempt_load(args.weights, map_location=device)  # load FP32 model
  File "/home/beltech/kapao/models/experimental.py", line 96, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
  File "/home/beltech/anaconda3/envs/kapao2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 692, in float
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
  File "/home/beltech/anaconda3/envs/kapao2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/beltech/anaconda3/envs/kapao2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/beltech/anaconda3/envs/kapao2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/beltech/anaconda3/envs/kapao2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/beltech/anaconda3/envs/kapao2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 692, in <lambda>
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
`

**Comment by wmcnally** [comment]
Have you tried using a newer version of PyTorch? E.g. 1.10?

**Comment by aafaqin** [comment]
Yes even after using the latest few version from pytorch website, same errors popped up.

**Comment by wmcnally** [comment]
Even with the latest version of cuda? Can you try 

`pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`

**Comment by wmcnally** [comment]
@aafaqin did the new version of cuda fix your issue?

**Comment by aafaqin** [comment]
Thanks for the response.
For me on RT3090 
`conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge`

This command worked better for me.
I was also getting 40-45 fps on the default flashmob youtube video
