### ISSUE TITLE
val.py PermissionErro

### ISSUE THREAD

**Issue by Flashan** [wmcnally/kapao#81]
Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
     0/299     1.98G   0.04683   0.06445   0.01968    0.1411        52       640: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 315/315 [01:07<00:00,  4.69it/s] 
Processing val images: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 135/135 [00:10<00:00, 13.02it/s]
Traceback (most recent call last):
  File "train.py", line 603, in <module>
    main(opt)
  File "train.py", line 501, in main
    train(opt.hyp, opt, device)
  File "train.py", line 352, in train
    results, maps, _ = val.run(data_dict,
  File "D:\anaconda3\envs\pytorch-gpu\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "D:\RunPrograms\kapao-master\val.py", line 283, in run
    with open(json_path, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Reza\\AppData\\Local\\Temp\\tmpt7tpns4i'

**Comment by Flashan** [comment]
chang line280 as 'tmp = tempfile.NamedTemporaryFile(mode='w+b',delete=False)'
train result as follow:
 Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
     0/299     1.98G   0.04687   0.06436   0.01966    0.1401        52       640: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 315/315 [01:00<00:00,  5.18it/s] 
Processing val images: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 135/135 [00:09<00:00, 13.95it/s] 
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
json_path== C:\Users\Reza\AppData\Local\Temp\tmpj7kggrx8
Loading and preparing results...
Traceback (most recent call last):
  File "train.py", line 603, in <module>
    main(opt)
  File "train.py", line 501, in main
    train(opt.hyp, opt, device)
  File "train.py", line 352, in train
    results, maps, _ = val.run(data_dict,
  File "D:\anaconda3\envs\pytorch-gpu\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "D:\RunPrograms\kapao-master\val.py", line 290, in run
    result = coco.loadRes(json_path)
  File "D:\anaconda3\envs\pytorch-gpu\lib\site-packages\pycocotools\coco.py", line 327, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set
