### ISSUE TITLE
'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by amirhosk** [wmcnally/kapao#9]
When I run any of demos, I get an error. Any suggestions?

(kapao) Me:~/kapao$ python demos/squash.py --display --fps
Traceback (most recent call last):
  File "demos/squash.py", line 83, in <module>
    stream = [s for s in yt.streams if s.itag == 137][0]  # 1080p, 25 fps
  File "/home/media/miniconda3/envs/kapao/lib/python3.6/site-packages/pytube/__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/media/miniconda3/envs/kapao/lib/python3.6/site-packages/pytube/__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/home/media/miniconda3/envs/kapao/lib/python3.6/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/home/media/miniconda3/envs/kapao/lib/python3.6/site-packages/pytube/cipher.py", line 44, in __init__
    self.throttling_array = get_throttling_function_array(js)
  File "/home/media/miniconda3/envs/kapao/lib/python3.6/site-packages/pytube/cipher.py", line 323, in get_throttling_function_array
    str_array = throttling_array_split(array_raw)
  File "/home/media/miniconda3/envs/kapao/lib/python3.6/site-packages/pytube/parser.py", line 158, in throttling_array_split
    match_start, match_end = match.span()
AttributeError: 'NoneType' object has no attribute 'span'

**Comment by wmcnally** [comment]
Are you connected to the internet?

**Comment by amirhosk** [comment]
Yes, do I need to update my pytube lib?

**Comment by wmcnally** [comment]
Perhaps. Please use this one, which has a recent patch: `$ pip install git+https://github.com/baxterisme/pytube`

**Comment by amirhosk** [comment]
Still doesn't work. How can I run it on an image in my pc to make sure the issue isn't relevant to pytube?

**Comment by wmcnally** [comment]
It's not working for me either. I can assure you it's a pytube issue. YouTube must have changed their formatting and therefore pytube requires a new patch. This must have happened today. I will look into a fix and additionally provide a general script to process a local video.

**Comment by wmcnally** [comment]
It worked for me today. Can you try again? Maybe youtube was down...

**Comment by amirhosk** [comment]
It's working for me as well, thanks

**Comment by wmcnally** [comment]
@amirhosk FYI I uploaded a static image demo

**Comment by amirhosk** [comment]
I just found it. sounds great. thanks!
